### Signup
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "email": "nourhasan1990s@gmail.com",
  "username": "nourirr",
  "password": "TestPassword123!"
} 


### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "nourhasan1990s@gmail.com",
  "password": "TestPassword123!"
}

### Refresh Token 
# The REST client must retain and send the HttpOnly cookie set by /login.
POST http://localhost:3000/api/auth/refresh
